d3.select("body")
    .append("svg")
    .attr("id", "carsScatter")
    .attr("width",600)
    .attr("height", 400)
let x = cars.map(d => d.disp)
let y = cars.map(d => d.mpg)
let disp = 
d3.scaleLinear()
    .domain(d3.extent(x))
    .range([5, 595])
let mpg = 
d3.scaleLinear()
    .domain(d3.extent(y))
    .range([5, 395])

d3.selectAll("svg#carsScatter")
    .selectAll("circle")
    .data(cars)
    .enter()
    .append("circle")
    .attr("cx", (d,i) => disp(x[i]))
    .attr("cy", (d,i) => mpg(y[i]))
    .attr("r", 5)
    .attr("stroke", "red")
    .attr("fill", "transparent")